### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by zapturk** [zapturk/frfn#1]
- [x] Error checking
- [x] Help flag
- [x] Force flag
- [x] Find and Replace mode
- [x] Preappend mode
- [ ] Append mode
- [x] Build for Windows
- [x] Build for Mac
- [x] Build for Linux
- [x] Install instructions
